const pptxgen = require("pptxgenjs");
const fs = require("fs");
const path = require("path");

const inputPath = process.argv[2];
const outputPath = process.argv[3];

if (!inputPath || !outputPath) {
  console.error("Usage: node generate_pptx.js <input.json> <output.pptx>");
  process.exit(1);
}

const data = JSON.parse(fs.readFileSync(inputPath, "utf-8"));

const DEFAULT_COLORS = {
  bgDark: "0F0B2E",
  bgMid: "1A1145",
  bgCard: "241B52",
  primary: "6366F1",
  accent: "8B5CF6",
  accentLight: "A78BFA",
  text: "F1F5F9",
  textMuted: "94A3B8",
  highlight: "22D3EE",
};

function buildColors(brandColors) {
  if (!brandColors || brandColors.length < 3) return DEFAULT_COLORS;
  return {
    bgDark: brandColors[0] || DEFAULT_COLORS.bgDark,
    bgMid: brandColors[1] || DEFAULT_COLORS.bgMid,
    bgCard: brandColors[1] || DEFAULT_COLORS.bgCard,
    primary: brandColors[2] || DEFAULT_COLORS.primary,
    accent: brandColors[3] || DEFAULT_COLORS.accent,
    accentLight: brandColors[3] || DEFAULT_COLORS.accentLight,
    text: brandColors[4] || DEFAULT_COLORS.text,
    textMuted: "94A3B8",
    highlight: brandColors[3] || DEFAULT_COLORS.highlight,
  };
}

const COLORS = buildColors(data.colors);

const pres = new pptxgen();
pres.layout = "LAYOUT_16x9";
pres.author = "RAG Presentation Generator";
pres.title = data.topic || "Generated Presentation";

function addDecoCircles(slide) {
  slide.addShape(pres.shapes.OVAL, {
    x: -1.5, y: -1.5, w: 4, h: 4,
    fill: { color: COLORS.primary, transparency: 85 },
  });
  slide.addShape(pres.shapes.OVAL, {
    x: 7.5, y: 3, w: 4, h: 4,
    fill: { color: COLORS.accent, transparency: 85 },
  });
}

function addAccentBar(slide, x, y, w) {
  slide.addShape(pres.shapes.RECTANGLE, {
    x, y, w: w || 2.5, h: 0.05,
    fill: { color: COLORS.primary },
  });
}

function renderCover(slide, s) {
  addDecoCircles(slide);
  slide.addText(s.headline || data.topic, {
    x: 0.8, y: 1.2, w: 8.4, h: 2.2,
    fontSize: 42, fontFace: "Trebuchet MS", color: COLORS.text,
    bold: true, align: "left", valign: "middle",
  });
  if (s.subheadline) {
    slide.addText(s.subheadline, {
      x: 0.8, y: 3.4, w: 7, h: 0.7,
      fontSize: 18, fontFace: "Calibri", color: COLORS.textMuted,
      align: "left",
    });
  }
  addAccentBar(slide, 0.8, 4.3, 2.5);
  slide.addText("Generated by RAG Presentation System", {
    x: 0.8, y: 4.7, w: 5, h: 0.5,
    fontSize: 11, fontFace: "Calibri", color: COLORS.textMuted, align: "left",
  });
}

function renderContent(slide, s) {
  slide.addText(s.headline, {
    x: 0.8, y: 0.4, w: 8.5, h: 0.8,
    fontSize: 32, fontFace: "Trebuchet MS", color: COLORS.text, bold: true, align: "left",
  });
  addAccentBar(slide, 0.8, 1.2, 1.8);

  const bullets = s.bullets || [];
  bullets.forEach((bullet, i) => {
    const yPos = 1.6 + i * 0.95;
    slide.addShape(pres.shapes.RECTANGLE, {
      x: 0.8, y: yPos, w: 8.4, h: 0.8,
      fill: { color: COLORS.bgCard },
    });
    slide.addShape(pres.shapes.RECTANGLE, {
      x: 0.8, y: yPos, w: 0.06, h: 0.8,
      fill: { color: i % 2 === 0 ? COLORS.primary : COLORS.accent },
    });
    slide.addText(bullet, {
      x: 1.1, y: yPos + 0.15, w: 7.8, h: 0.5,
      fontSize: 16, fontFace: "Calibri", color: COLORS.text, align: "left", valign: "middle",
    });
  });
}

function renderStats(slide, s) {
  slide.addText(s.headline, {
    x: 0.8, y: 0.4, w: 8.5, h: 0.8,
    fontSize: 32, fontFace: "Trebuchet MS", color: COLORS.text, bold: true, align: "left",
  });
  addAccentBar(slide, 0.8, 1.2, 1.8);

  const stats = s.stats || [];
  stats.forEach((stat, i) => {
    const col = i % 2;
    const row = Math.floor(i / 2);
    const xPos = 0.8 + col * 4.5;
    const yPos = 1.6 + row * 1.85;

    slide.addShape(pres.shapes.RECTANGLE, {
      x: xPos, y: yPos, w: 4.1, h: 1.6,
      fill: { color: COLORS.bgCard },
    });
    slide.addShape(pres.shapes.RECTANGLE, {
      x: xPos, y: yPos, w: 0.07, h: 1.6,
      fill: { color: COLORS.primary },
    });
    slide.addText(stat.value, {
      x: xPos + 0.3, y: yPos + 0.2, w: 3.5, h: 0.7,
      fontSize: 36, fontFace: "Trebuchet MS", color: COLORS.highlight,
      bold: true, align: "left", valign: "middle",
    });
    slide.addText(stat.label, {
      x: xPos + 0.3, y: yPos + 0.95, w: 3.5, h: 0.45,
      fontSize: 14, fontFace: "Calibri", color: COLORS.textMuted, align: "left",
    });
  });
}

function renderList(slide, s) {
  slide.addText(s.headline, {
    x: 0.8, y: 0.4, w: 8.5, h: 0.8,
    fontSize: 32, fontFace: "Trebuchet MS", color: COLORS.text, bold: true, align: "left",
  });
  addAccentBar(slide, 0.8, 1.2, 1.8);

  const items = s.bullets || [];
  items.forEach((item, i) => {
    const yPos = 1.6 + i * 0.95;
    slide.addShape(pres.shapes.RECTANGLE, {
      x: 0.8, y: yPos, w: 0.55, h: 0.55,
      fill: { color: COLORS.bgCard },
    });
    slide.addText(String(i + 1).padStart(2, "0"), {
      x: 0.8, y: yPos, w: 0.55, h: 0.55,
      fontSize: 14, fontFace: "Consolas", color: COLORS.highlight,
      align: "center", valign: "middle",
    });
    slide.addText(item, {
      x: 1.55, y: yPos + 0.05, w: 7.5, h: 0.5,
      fontSize: 16, fontFace: "Calibri", color: COLORS.text, align: "left", valign: "middle",
    });
  });

  slide.addShape(pres.shapes.OVAL, {
    x: 7.8, y: 1.5, w: 3.2, h: 3.2,
    fill: { color: COLORS.accent, transparency: 90 },
  });
}

function renderComparison(slide, s) {
  slide.addText(s.headline, {
    x: 0.8, y: 0.4, w: 8.5, h: 0.8,
    fontSize: 32, fontFace: "Trebuchet MS", color: COLORS.text, bold: true, align: "left",
  });
  addAccentBar(slide, 0.8, 1.2, 1.8);

  const items = s.bullets || [];
  items.forEach((item, i) => {
    const xPos = 0.6 + i * 2.35;
    const maxCols = Math.min(items.length, 4);
    const colW = (9 - 0.6) / maxCols - 0.2;
    const realX = 0.6 + i * (colW + 0.2);

    slide.addShape(pres.shapes.RECTANGLE, {
      x: realX, y: 1.6, w: colW, h: 3.4,
      fill: { color: COLORS.bgCard },
    });
    const colColor = [COLORS.highlight, COLORS.primary, COLORS.accent, COLORS.accentLight][i % 4];
    slide.addShape(pres.shapes.RECTANGLE, {
      x: realX, y: 1.6, w: colW, h: 0.06,
      fill: { color: colColor },
    });
    slide.addText(item, {
      x: realX + 0.2, y: 1.9, w: colW - 0.4, h: 2.8,
      fontSize: 14, fontFace: "Calibri", color: COLORS.textMuted,
      align: "left", valign: "top",
    });
  });
}

function renderClosing(slide, s) {
  addDecoCircles(slide);
  slide.addText(s.headline || "Thank You", {
    x: 0.8, y: 1.5, w: 8.4, h: 1.5,
    fontSize: 38, fontFace: "Trebuchet MS", color: COLORS.text,
    bold: true, align: "left", valign: "middle",
  });
  if (s.subheadline) {
    slide.addText(s.subheadline, {
      x: 0.8, y: 3.2, w: 7, h: 0.7,
      fontSize: 18, fontFace: "Calibri", color: COLORS.textMuted, align: "left",
    });
  }
  addAccentBar(slide, 0.8, 4.0, 2.5);
}

const slides = data.slides || [];

slides.forEach((s) => {
  const slide = pres.addSlide();
  slide.background = { color: COLORS.bgDark };

  const type = (s.slide_type || "content").toLowerCase();

  switch (type) {
    case "cover":
      renderCover(slide, s);
      break;
    case "stats":
      renderStats(slide, s);
      break;
    case "list":
      renderList(slide, s);
      break;
    case "comparison":
      renderComparison(slide, s);
      break;
    case "closing":
      renderClosing(slide, s);
      break;
    default:
      renderContent(slide, s);
      break;
  }

  if (s.notes) {
    slide.addNotes(s.notes);
  }
});

pres.writeFile({ fileName: outputPath })
  .then(() => {
    console.log(`PPTX generated: ${outputPath}`);
    process.exit(0);
  })
  .catch((err) => {
    console.error("Error generating PPTX:", err);
    process.exit(1);
  });
